basePath: /api/v1
definitions:
  main.PingResponse:
    properties:
      message:
        description: return message
        type: string
    type: object
host: api.leetcode.cn
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PingResponse'
      summary: ping example
      tags:
      - example
swagger: "2.0"
